FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD start.sh /code/
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/
EXPOSE 8000
CMD gunicorn firstdjango.wsgi:application --bind 0.0.0.0:8000 --workers 3
